spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organizationmanagement
    username: root
    password: 1234
  application:
    name: user-application-server



server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/